const char *colConversion_kernel =
"#version 310 es\n"
"#define LOCAL_SIZE 1024\n"
"\n"
"#extension GL_ANDROID_extension_pack_es31a : require\n"
"layout(local_size_x = LOCAL_SIZE) in;\n"
"layout(binding=0, rgba32f) uniform mediump readonly imageBuffer velocity_buffer;\n"
"layout(binding=1, rgba32f) uniform mediump writeonly imageBuffer position_buffer;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 vel = imageLoad(velocity_buffer, int(gl_GlobalInvocationID.x));\n"
"	vel += vec4(0.0f, 0.0f, 25.0f, 12.5f);\n"
"	vec4 result = vec4(gl_LocalInvocationID.x, gl_WorkGroupID.x, gl_LocalInvocationID.y, gl_WorkGroupID.y);\n"
"	imageStore(position_buffer, int(gl_GlobalInvocationID.x), result);\n"
"}\n";
