 
#include "colConversion.h"
#include "getColorPurity.h"
#include "copyInGL.h"
#include "getTransValidity.h"
#include "getLineCrossing.h"
#include "getPatternIndicator.h"
#include "plotCorners.h"
#include "markDetectedCorners.h"
#include "cornersZero.h"
#include "getBlockCorners.h"
#include "refineCorners.h"
#include "getNCorners.h"
#include "getCorners.h"
#include "getLinePtAssignment.h"
