static const char *getCorners_kernel =
"#version 310 es\n"
"\n"
"#extension GL_ANDROID_extension_pack_es31a : require\n"
"layout(local_size_x = 4, local_size_y = 2) in;\n"
"layout(binding=0, rgba32f) uniform mediump readonly image2D input_image;\n"
"layout(binding=1, rgba32f) uniform mediump writeonly image2D output_image;\n"
"layout(std430, binding = 2) buffer X_ssbo {float X[];};\n"
"layout(std430, binding = 3) buffer Y_ssbo {float Y[];};\n"
"layout(std430, binding = 4) buffer C_ssbo {int C[];};\n"
"layout(std430, binding = 5) buffer nPts_ssbo {int nPts[];};\n"
"void main()\n"
"{	\n"
"	int sz_x = int((gl_NumWorkGroups.x*gl_WorkGroupSize.x));\n"
"\t\tint sz_y = int((gl_NumWorkGroups.y*gl_WorkGroupSize.y));\n"
"	\n"
"\t\tint idx = int(gl_GlobalInvocationID.x);\n"
"\t\tint idy = int(gl_GlobalInvocationID.y);\n"
"\n"
"\t\tint id = idy*sz_x + idx;\n"
"\t\t\n"
"	int numPts_old=0;\n"
"\t\tif(C[id]==1){\n"
"\t\t\t\tnumPts_old = atomicAdd(nPts[0],1);\n"
"\t\t\t\t X[numPts_old]=float(idx);\n"
"\t\t\t\t Y[numPts_old]=float(idy);\n"
"\t\t}\n"
"}\n";
