static const char *markDetectedCorners_kernel =
"#version 310 es\n"
"#define LOCAL_SIZE 1\n"
"\n"
"#extension GL_ANDROID_extension_pack_es31a : require\n"
"layout(local_size_x = LOCAL_SIZE, local_size_y = LOCAL_SIZE) in;\n"
"layout(binding=1, rgba32f) uniform mediump writeonly image2D output_image;\n"
"layout(std430, binding = 2) buffer pts_ssbo {float pts[];};\n"
"void main()\n"
"{\n"
"\t\tivec2 pos;\n"
"\t\tvec4 pixelf;\n"
"\t\t\n"
"\t\tpixelf.x = 0.0;\n"
"\t\tpixelf.y = 0.0;\n"
"\t\tpixelf.z = 0.0;\n"
"\t\tpixelf.w = 1.0;\n"
"\t\t\n"
"\t\tint id = int(gl_GlobalInvocationID.x);\n"
"\t\t\n"
"\t\tint x,y;\n"
"\t\tx=int(floor(pts[2*id]+0.5));\n"
"\t\ty=int(floor(pts[2*id+1]+0.5));\n"
"\t\t\t\t\n"
"\t\tint s=5;\n"
"\t\tint flag=0;\n"
"\t\tfor(int i=-s;i<s;i++){\n"
"\t\t\t\tfor(int j=-s;j<s;j++){\n"
"\t\t\t\t\t\tif(x+i>=0 && x+i<1080 && y+j>=0 && y+j<1920){\n"
"\t\t\t\t\t\t\t\tpos.x=y+j;\n"
"\t\t\t\t\t\t\t\tpos.y=x+i;\n"
"\t\t\t\t\t\t\t\tpixelf.x = 1.0;\n"
"\t\t\t\t\t\t\t\tpixelf.y = 1.0;\n"
"\t\t\t\t\t\t\t\tpixelf.z = 1.0;\n"
"\t\t\t\t\t\t\t\tpixelf.w = 1.0;\n"
"				imageStore(output_image, pos, pixelf);\n"
"\t\t\t\t\t\t\t\t//write_imagef(out_image, pos, pixelf);\n"
"\t\t\t\t\t\t}\n"
"\t\t\t\t}\n"
"\t\t}\t\n"
"}\n";
