var hierarchy =
[
    [ "_cl_buffer_region", "struct__cl__buffer__region.html", null ],
    [ "_cl_dx9_surface_info_khr", "struct__cl__dx9__surface__info__khr.html", null ],
    [ "_cl_image_desc", "struct__cl__image__desc.html", null ],
    [ "_cl_image_format", "struct__cl__image__format.html", null ],
    [ "_cl_mem_ext_host_ptr", "struct__cl__mem__ext__host__ptr.html", null ],
    [ "_cl_mem_ion_host_ptr", "struct__cl__mem__ion__host__ptr.html", null ],
    [ "JNICLTracker::CLManager::_Params_", "struct_j_n_i_c_l_tracker_1_1_c_l_manager_1_1___params__.html", null ],
    [ "patterntracker.stereo.Algo3D", "classpatterntracker_1_1stereo_1_1_algo3_d.html", null ],
    [ "patterntracker.camera.CameraManager", "classpatterntracker_1_1camera_1_1_camera_manager.html", null ],
    [ "patterntracker.stereo.CameraModelParams", "classpatterntracker_1_1stereo_1_1_camera_model_params.html", null ],
    [ "cl_char16", "unioncl__char16.html", null ],
    [ "cl_char2", "unioncl__char2.html", null ],
    [ "cl_char4", "unioncl__char4.html", null ],
    [ "cl_char8", "unioncl__char8.html", null ],
    [ "cl_double16", "unioncl__double16.html", null ],
    [ "cl_double2", "unioncl__double2.html", null ],
    [ "cl_double4", "unioncl__double4.html", null ],
    [ "cl_double8", "unioncl__double8.html", null ],
    [ "cl_float16", "unioncl__float16.html", null ],
    [ "cl_float2", "unioncl__float2.html", null ],
    [ "cl_float4", "unioncl__float4.html", null ],
    [ "cl_float8", "unioncl__float8.html", null ],
    [ "cl_int16", "unioncl__int16.html", null ],
    [ "cl_int2", "unioncl__int2.html", null ],
    [ "cl_int4", "unioncl__int4.html", null ],
    [ "cl_int8", "unioncl__int8.html", null ],
    [ "cl_long16", "unioncl__long16.html", null ],
    [ "cl_long2", "unioncl__long2.html", null ],
    [ "cl_long4", "unioncl__long4.html", null ],
    [ "cl_long8", "unioncl__long8.html", null ],
    [ "cl_short16", "unioncl__short16.html", null ],
    [ "cl_short2", "unioncl__short2.html", null ],
    [ "cl_short4", "unioncl__short4.html", null ],
    [ "cl_short8", "unioncl__short8.html", null ],
    [ "cl_uchar16", "unioncl__uchar16.html", null ],
    [ "cl_uchar2", "unioncl__uchar2.html", null ],
    [ "cl_uchar4", "unioncl__uchar4.html", null ],
    [ "cl_uchar8", "unioncl__uchar8.html", null ],
    [ "cl_uint16", "unioncl__uint16.html", null ],
    [ "cl_uint2", "unioncl__uint2.html", null ],
    [ "cl_uint4", "unioncl__uint4.html", null ],
    [ "cl_uint8", "unioncl__uint8.html", null ],
    [ "cl_ulong16", "unioncl__ulong16.html", null ],
    [ "cl_ulong2", "unioncl__ulong2.html", null ],
    [ "cl_ulong4", "unioncl__ulong4.html", null ],
    [ "cl_ulong8", "unioncl__ulong8.html", null ],
    [ "cl_ushort16", "unioncl__ushort16.html", null ],
    [ "cl_ushort2", "unioncl__ushort2.html", null ],
    [ "cl_ushort4", "unioncl__ushort4.html", null ],
    [ "cl_ushort8", "unioncl__ushort8.html", null ],
    [ "JNICLTracker::CLManager", "class_j_n_i_c_l_tracker_1_1_c_l_manager.html", null ],
    [ "JNICLTracker::CLTracker", "class_j_n_i_c_l_tracker_1_1_c_l_tracker.html", null ],
    [ "patterntracker.ColorGridTracker", "classpatterntracker_1_1_color_grid_tracker.html", null ],
    [ "Comparable", null, [
      [ "patterntracker.ColorGridTracker.Paird", "classpatterntracker_1_1_color_grid_tracker_1_1_paird.html", null ]
    ] ],
    [ "JNICLTracker::CLTracker::CornerRefinementParam", "struct_j_n_i_c_l_tracker_1_1_c_l_tracker_1_1_corner_refinement_param.html", null ],
    [ "JNICLTracker::CLTracker::GPUVars", "struct_j_n_i_c_l_tracker_1_1_c_l_tracker_1_1_g_p_u_vars.html", null ],
    [ "JNICLTracker::CLTracker::int2", "struct_j_n_i_c_l_tracker_1_1_c_l_tracker_1_1int2.html", null ],
    [ "patterntracker.util.IOUtil", "classpatterntracker_1_1util_1_1_i_o_util.html", null ],
    [ "patterntracker.predictor.KalamanFilter", "classpatterntracker_1_1predictor_1_1_kalaman_filter.html", null ],
    [ "patterntracker.predictor.LinearPrediction", "classpatterntracker_1_1predictor_1_1_linear_prediction.html", null ],
    [ "Renderer", null, [
      [ "patterntracker.CustomGLRenderer", "classpatterntracker_1_1_custom_g_l_renderer.html", null ]
    ] ],
    [ "patterntracker.camera.ShaderManager", "classpatterntracker_1_1camera_1_1_shader_manager.html", null ],
    [ "patterntracker.util.TUtil", "classpatterntracker_1_1util_1_1_t_util.html", null ],
    [ "Activity", null, [
      [ "patterntracker.MainTrackerActivity", "classpatterntracker_1_1_main_tracker_activity.html", null ]
    ] ],
    [ "GLSurfaceView", null, [
      [ "patterntracker.CustomGLSurfaceView", "classpatterntracker_1_1_custom_g_l_surface_view.html", null ]
    ] ],
    [ "Handler", null, [
      [ "patterntracker.util.HandlerExtension", "classpatterntracker_1_1util_1_1_handler_extension.html", null ]
    ] ]
];